const favorites = [
    { id: 'abc-news-au', name: 'ABC News (AU)', favorite: false },
    { id: 'ars-technica', name: 'Ars Technica', favorite: false },
    { id: 'associated-press', name: 'Associated Press', favorite: false },
    { id: 'bbc-news', name: 'BBC News', favorite: false },
    { id: 'bbc-sport', name: 'BBC Sport', favorite: false },
    { id: 'bloomberg', name: 'Bloomberg', favorite: false },
    { id: 'business-insider', name: 'Business Insider', favorite: false },
    { id: 'business-insider-uk', name: 'Business Insider (UK)', favorite: false },
    { id: 'buzzfeed', name: 'Buzzfeed', favorite: false },
    { id: 'cnbc', name: 'CNBC', favorite: false },
    { id: 'cnn', name: 'CNN', favorite: false },
    { id: 'daily-mail', name: 'Daily Mail', favorite: false },
    { id: 'engadget', name: 'Engadget', favorite: false },
    { id: 'entertainment-weekly', name: 'Entertainment Weekly', favorite: false },
    { id: 'espn', name: 'ESPN', favorite: false },
    { id: 'espn-cric-info', name: 'ESPN Cric Info', favorite: false },
    { id: 'financial-times', name: 'Financial Times', favorite: false },    
    { id: 'football-italia', name: 'Football Italia', favorite: false },
    { id: 'fortune', name: 'Fortune', favorite: false },
    { id: 'four-four-two', name: 'FourFourTwo', favorite: false },
    { id: 'fox-sports', name: 'Fox Sports', favorite: false },
    { id: 'google-news', name: 'Google News', favorite: false },
    { id: 'hacker-news', name: 'Hacker News', favorite: false },
    { id: 'ign', name: 'IGN', favorite: false },
    { id: 'independent', name: 'Independent', favorite: false },
    { id: 'mashable', name: 'Mashable', favorite: false },
    { id: 'metro', name: 'Metro', favorite: false },
    { id: 'mirror', name: 'Mirror', favorite: false },
    { id: 'mtv-news', name: 'MTV News', favorite: false },
    { id: 'mtv-news-uk', name: 'MTV News (UK)', favorite: false },
    { id: 'national-geographic', name: 'National Geographic', favorite: false },
    { id: 'new-scientist', name: 'New Scientist', favorite: false },
    { id: 'newsweek', name: 'Newsweek', favorite: false },
    { id: 'new-york-magazine', name: 'New York Magazine', favorite: false }, 
    { id: 'nfl-news', name: 'NFL News', favorite: false },
    { id: 'polygon', name: 'Polygon', favorite: false },
    { id: 'recode', name: 'Recode', favorite: false },
    { id: 'reddit-r-all', name: 'Reddit /r/all', favorite: false },
    { id: 'reuters', name: 'Reuters', favorite: false },
    { id: 'sky-news', name: 'Sky News', favorite: false },
    { id: 'sky-sports-news', name: 'Sky Sports News', favorite: false },
    { id: 'talksport', name: 'TalkSport', favorite: false },
    { id: 'techcrunch', name: 'TechCrunch', favorite: false },
    { id: 'techradar', name: 'TechRadar', favorite: false },
    { id: 'the-economist', name: 'The Economist', favorite: false },
    { id: 'the-guardian-au', name: 'The Guardian (AU)', favorite: false },
    { id: 'the-guardian-uk', name: 'The Guardian (UK)', favorite: false },
    { id: 'the-hindu', name: 'The Hindu', favorite: false },
    { id: 'the-huffington-post', name: 'The Huffington Post', favorite: false },
    { id: 'the-lad-bible', name: 'The Lad Bible', favorite: false },
    { id: 'the-new-york-times', name: 'The New York Times', favorite: false },
    { id: 'the-next-web', name: 'The Next Web', favorite: false },
    { id: 'the-sport-bible', name: 'The Sport Bible', favorite: false },
    { id: 'the-telegraph', name: 'The Telegraph', favorite: false },
    { id: 'the-times-of-india', name: 'The Times of India', favorite: false },
    { id: 'the-verge', name: 'The Verge', favorite: false },
    { id: 'the-wall-street-journal', name: 'The Wall Street Journal', favorite: false },
    { id: 'the-washington-post', name: 'The Washington Post', favorite: false },
    { id: 'time', name: 'Time', favorite: false },
    { id: 'usa-today', name: 'USA Today', favorite: false }
]

module.exports = favorites;
